# Generated by Django 2.0.4 on 2018-04-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cafe_com_leite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mancada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('mancada', models.TextField()),
                ('perdoada', models.BooleanField(default=False)),
                ('individuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mancadas.Individuo')),
            ],
        ),
    ]
